name: yuonsoft
description: yuonsoft homepage

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.4
  file_picker: ^4.3.0
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.4
  flutterfire_ui: ^0.2.0+2
  get: ^4.5.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
